import { VocabularyWord } from './types';

export const INITIAL_VOCABULARY: VocabularyWord[] = [
  {
    id: '1',
    character: '是',
    pinyin: 'shì',
    definition: 'là (thì, đúng, vâng)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我是越南人。',
    exampleVietnamese: 'Tôi là người Việt Nam.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '2',
    character: '不',
    pinyin: 'bù',
    definition: 'không (bất, dùng để phủ định)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我不是老师。',
    exampleVietnamese: 'Tôi không phải là giáo viên.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '3',
    character: '吗',
    pinyin: 'ma',
    definition: 'không? (trợ từ dùng ở cuối câu hỏi)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '你是学生吗？',
    exampleVietnamese: 'Bạn là học sinh phải không?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '4',
    character: '也',
    pinyin: 'yě',
    definition: 'cũng (dùng biểu thị sự tương đồng)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我也是学生。',
    exampleVietnamese: 'Tôi cũng là học sinh.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '5',
    character: '有',
    pinyin: 'yǒu',
    definition: 'có (sở hữu, tồn tại)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我有汉语老师。',
    exampleVietnamese: 'Tôi có giáo viên tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '6',
    character: '怎么',
    pinyin: 'zěnme',
    definition: 'thế nào, làm sao, như thế nào',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '这个汉语字怎么说？',
    exampleVietnamese: 'Chữ tiếng Trung này nói thế nào?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '7',
    character: '会',
    pinyin: 'huì',
    definition: 'biết, có thể (thông qua học tập)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我会说一点汉语。',
    exampleVietnamese: 'Tôi biết nói một chút tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '8',
    character: '在',
    pinyin: 'zài',
    definition: 'ở, tại, đang (ở vị trí, hành động đang diễn ra)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '老师在公司工作。',
    exampleVietnamese: 'Giáo viên đang làm việc ở công ty.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '9',
    character: '来',
    pinyin: 'lái',
    definition: 'đến, lại (hành động hướng về phía người nói)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '你来我家吧。',
    exampleVietnamese: 'Bạn đến nhà tôi đi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '10',
    character: '从',
    pinyin: 'cóng',
    definition: 'từ (chỉ điểm xuất phát)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我从越南来。',
    exampleVietnamese: 'Tôi đến từ Việt Nam.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '11',
    character: '哪儿',
    pinyin: 'nǎr',
    definition: 'ở đâu, chỗ nào',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '现在你去哪儿？',
    exampleVietnamese: 'Bây giờ bạn đi đâu?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '12',
    character: '现在',
    pinyin: 'xiànzài',
    definition: 'bây giờ, hiện tại',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '现在是学习时间。',
    exampleVietnamese: 'Bây giờ là thời gian học tập.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '13',
    character: '这',
    pinyin: 'zhè',
    definition: 'đây, cái này (chỉ vật ở gần)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '这是我们的公司。',
    exampleVietnamese: 'Đây là công ty của chúng tôi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '14',
    character: '那',
    pinyin: 'nà',
    definition: 'kia, cái kia (chỉ vật ở xa)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '那是陈老师吗？',
    exampleVietnamese: 'Kia là giáo viên Trần phải không?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '15',
    character: '人',
    pinyin: 'rén',
    definition: 'người (nhân)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '那个人是谁？',
    exampleVietnamese: 'Người kia là ai thế?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '16',
    character: '中国',
    pinyin: 'Zhōngguó',
    definition: 'Trung Quốc',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '有些学生去中国学习。',
    exampleVietnamese: 'Một số học sinh đi học ở Trung Quốc.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '17',
    character: '越南',
    pinyin: 'Yuènán',
    definition: 'Việt Nam',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我是越南人，我爱越南。',
    exampleVietnamese: 'Tôi là người Việt Nam, tôi yêu Việt Nam.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '18',
    character: '汉语',
    pinyin: 'Hànyǔ',
    definition: 'tiếng Trung, tiếng Hoa (Hán ngữ)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '他在公司说汉语。',
    exampleVietnamese: 'Anh ấy nói tiếng Trung ở công ty.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '19',
    character: '工作',
    pinyin: 'gōngzuò',
    definition: 'công việc, làm việc',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '你的工作是什么？',
    exampleVietnamese: 'Công việc của bạn là gì?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '20',
    character: '学习',
    pinyin: 'xuéxí',
    definition: 'học tập, học hỏi',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我想学习说汉语。',
    exampleVietnamese: 'Tôi muốn học nói tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '21',
    character: '学生',
    pinyin: 'xuéshēng',
    definition: 'học sinh, sinh viên',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我们都是中国公司的学生。',
    exampleVietnamese: 'Chúng tôi đều là thực tập sinh/học viên của công ty Trung Quốc.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '22',
    character: '老师',
    pinyin: 'lǎoshī',
    definition: 'giáo viên, thầy cô giáo',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '王老师是很好的人。',
    exampleVietnamese: 'Thầy Vương là một người rất tốt.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '23',
    character: '公司',
    pinyin: 'gōngsī',
    definition: 'công ty',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '你在哪个公司工作？',
    exampleVietnamese: 'Bạn làm việc ở công ty nào?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '24',
    character: '说',
    pinyin: 'shuō',
    definition: 'nói',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '请慢一点说。',
    exampleVietnamese: 'Xin vui lòng nói chậm lại một chút.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '25',
    character: '一点',
    pinyin: 'yīdiǎn',
    definition: 'một chút, một ít',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我会说一点点汉语。',
    exampleVietnamese: 'Tôi biết nói một chút xíu tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '26',
    character: '时间',
    pinyin: 'shíjiān',
    definition: 'thời gian',
    category: 'Bài 2: Thời gian',
    exampleChinese: '我没有时间。',
    exampleVietnamese: 'Tôi không có thời gian.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '27',
    character: '今天',
    pinyin: 'jīntiān',
    definition: 'hôm nay',
    category: 'Bài 2: Thời gian',
    exampleChinese: '今天我们去哪儿？',
    exampleVietnamese: 'Hôm nay chúng ta đi đâu?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '28',
    character: '明天',
    pinyin: 'míngtiān',
    definition: 'ngày mai',
    category: 'Bài 2: Thời gian',
    exampleChinese: '明天你来我家吗？',
    exampleVietnamese: 'Ngày mai bạn đến nhà tôi không?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '29',
    character: '昨天',
    pinyin: 'zuótiān',
    definition: 'hôm qua',
    category: 'Bài 2: Thời gian',
    exampleChinese: '昨天我没去公司。',
    exampleVietnamese: 'Hôm qua tôi không đến công ty.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '30',
    character: '现在',
    pinyin: 'xiànzài',
    definition: 'bây giờ',
    category: 'Bài 2: Thời gian',
    exampleChinese: '现在是十二点。',
    exampleVietnamese: 'Bây giờ là 12 giờ.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '31',
    character: '以前',
    pinyin: 'yǐqián',
    definition: 'trước đây',
    category: 'Bài 2: Thời gian',
    exampleChinese: '以前他是我的学生。',
    exampleVietnamese: 'Trước đây anh ấy là học sinh của tôi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '32',
    character: '以后',
    pinyin: 'yǐhòu',
    definition: 'sau này',
    category: 'Bài 2: Thời gian',
    exampleChinese: '以后我想去中国。',
    exampleVietnamese: 'Sau này tôi muốn đi Trung Quốc.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '33',
    character: '早上',
    pinyin: 'zǎoshang',
    definition: 'buổi sáng',
    category: 'Bài 2: Thời gian',
    exampleChinese: '早上我六点起床。',
    exampleVietnamese: 'Buổi sáng tôi thức dậy lúc 6 giờ.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '34',
    character: '中午',
    pinyin: 'zhōngwǔ',
    definition: 'buổi trưa',
    category: 'Bài 2: Thời gian',
    exampleChinese: '中午你在哪儿吃饭？',
    exampleVietnamese: 'Buổi trưa bạn ăn cơm ở đâu?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '35',
    character: '下午',
    pinyin: 'xiàwǔ',
    definition: 'buổi chiều',
    category: 'Bài 2: Thời gian',
    exampleChinese: '下午我有汉语课。',
    exampleVietnamese: 'Buổi chiều tôi có tiết học tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '36',
    character: '晚上',
    pinyin: 'wǎnshang',
    definition: 'buổi tối',
    category: 'Bài 2: Thời gian',
    exampleChinese: '晚上我学习汉语。',
    exampleVietnamese: 'Buổi tối tôi học tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '37',
    character: '上午',
    pinyin: 'shàngwǔ',
    definition: 'buổi sáng (trước trưa)',
    category: 'Bài 2: Thời gian',
    exampleChinese: '上午老师在公司。',
    exampleVietnamese: 'Buổi sáng giáo viên ở công ty.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '38',
    character: '分钟',
    pinyin: 'fēnzhōng',
    definition: 'phút',
    category: 'Bài 2: Thời gian',
    exampleChinese: '请等我十分钟。',
    exampleVietnamese: 'Xin vui lòng đợi tôi 10 phút.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '39',
    character: '小时',
    pinyin: 'xiǎoshí',
    definition: 'giờ (tiếng)',
    category: 'Bài 2: Thời gian',
    exampleChinese: '我学习了两个小时。',
    exampleVietnamese: 'Tôi đã học trong hai tiếng đồng hồ.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '40',
    character: '天',
    pinyin: 'tiān',
    definition: 'ngày',
    category: 'Bài 2: Thời gian',
    exampleChinese: '一天有二十四个小时。',
    exampleVietnamese: 'Một ngày có 24 tiếng đồng hồ.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '41',
    character: '星期',
    pinyin: 'xīngqī',
    definition: 'tuần',
    category: 'Bài 2: Thời gian',
    exampleChinese: '这个星期我很忙。',
    exampleVietnamese: 'Tuần này tôi rất bận.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '42',
    character: '月',
    pinyin: 'yuè',
    definition: 'tháng',
    category: 'Bài 2: Thời gian',
    exampleChinese: '今年五月我去中国。',
    exampleVietnamese: 'Tháng 5 năm nay tôi đi Trung Quốc.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '43',
    character: '年',
    pinyin: 'nián',
    definition: 'năm',
    category: 'Bài 2: Thời gian',
    exampleChinese: '他在中国学习了一年。',
    exampleVietnamese: 'Anh ấy đã học ở Trung Quốc một năm.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '44',
    character: '早',
    pinyin: 'zǎo',
    definition: 'sớm',
    category: 'Bài 2: Thời gian',
    exampleChinese: '你来得很早。',
    exampleVietnamese: 'Bạn đến rất sớm.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '45',
    character: '晚',
    pinyin: 'wǎn',
    definition: 'muộn / tối',
    category: 'Bài 2: Thời gian',
    exampleChinese: '现在很晚了，去睡觉吧。',
    exampleVietnamese: 'Bây giờ muộn rồi, đi ngủ thôi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '46',
    character: '马上',
    pinyin: 'mǎshàng',
    definition: 'ngay lập tức',
    category: 'Bài 2: Thời gian',
    exampleChinese: '我马上来。',
    exampleVietnamese: 'Tôi đến ngay lập tức.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '47',
    character: '常常',
    pinyin: 'chángcháng',
    definition: 'thường xuyên',
    category: 'Bài 2: Thời gian',
    exampleChinese: '我常常和朋友说汉语。',
    exampleVietnamese: 'Tôi thường xuyên nói tiếng Trung với bạn bè.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '48',
    character: '有时候',
    pinyin: 'yǒu shíhou',
    definition: 'đôi khi',
    category: 'Bài 2: Thời gian',
    exampleChinese: '有时候我不想工作。',
    exampleVietnamese: 'Đôi khi tôi không muốn làm việc.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '49',
    character: '每天',
    pinyin: 'měitiān',
    definition: 'mỗi ngày',
    category: 'Bài 2: Thời gian',
    exampleChinese: '我每天都学习汉语。',
    exampleVietnamese: 'Tôi học tiếng Trung mỗi ngày.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '50',
    character: '时候',
    pinyin: 'shíhou',
    definition: 'lúc, thời điểm',
    category: 'Bài 2: Thời gian',
    exampleChinese: '你什么时候去？',
    exampleVietnamese: 'Khi nào bạn đi?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  }
];
