import { VocabularyWord } from './types';

export const INITIAL_VOCABULARY: VocabularyWord[] = [
  {
    id: '0_1',
    character: '我',
    pinyin: 'wǒ',
    definition: 'Tôi',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '我是学生。',
    examplePinyin: 'Wǒ shì xuésheng.',
    exampleVietnamese: 'Tôi là học sinh.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_2',
    character: '你',
    pinyin: 'nǐ',
    definition: 'Bạn',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '你好！',
    examplePinyin: 'Nǐ hǎo!',
    exampleVietnamese: 'Xin chào!',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_3',
    character: '您',
    pinyin: 'nín',
    definition: 'Ngài / bạn (lịch sự)',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '老师，您好！',
    examplePinyin: 'Lǎoshī, nín hǎo!',
    exampleVietnamese: 'Chào thầy cô ạ!',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_4',
    character: '他',
    pinyin: 'tā',
    definition: 'Anh ấy',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '他是我的同学。',
    examplePinyin: 'Tā shì wǒ de tóngxué.',
    exampleVietnamese: 'Anh ấy là bạn học của tôi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_5',
    character: '她',
    pinyin: 'tā',
    definition: 'Cô ấy',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '她是我的老师。',
    examplePinyin: 'Tā shì wǒ de lǎoshī.',
    exampleVietnamese: 'Cô ấy là giáo viên của tôi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_6',
    character: '我们',
    pinyin: 'wǒmen',
    definition: 'Chúng tôi',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '我们都是越南人。',
    examplePinyin: 'Wǒmen dōu shì Yuènánrén.',
    exampleVietnamese: 'Chúng tôi đều là người Việt Nam.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_7',
    character: '你们',
    pinyin: 'nǐmen',
    definition: 'Các bạn',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '你们好！',
    examplePinyin: 'Nǐmen hǎo!',
    exampleVietnamese: 'Chào các bạn!',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_8',
    character: '他们',
    pinyin: 'tāmen',
    definition: 'Bọn họ (nam / chung)',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '他们去学校。',
    examplePinyin: 'Tāmen qù xuéxiào.',
    exampleVietnamese: 'Bọn họ đi đến trường.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_9',
    character: '她们',
    pinyin: 'tāmen',
    definition: 'Bọn họ (nữ)',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '她们是学生。',
    examplePinyin: 'Tāmen shì xuésheng.',
    exampleVietnamese: 'Bọn họ (nữ) là học sinh.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_10',
    character: '你好',
    pinyin: 'nǐ hǎo',
    definition: 'Xin chào',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '你好，我叫安。',
    examplePinyin: 'Nǐ hǎo, wǒ jiào Ān.',
    exampleVietnamese: 'Xin chào, tôi tên An.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_11',
    character: '您好',
    pinyin: 'nín hǎo',
    definition: 'Xin chào (lịch sự)',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '老师，您好！',
    examplePinyin: 'Lǎoshī, nín hǎo!',
    exampleVietnamese: 'Em chào thầy cô ạ!',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_12',
    character: '早上好',
    pinyin: 'zǎoshang hǎo',
    definition: 'Chào buổi sáng',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '早上好，安！',
    examplePinyin: 'Zǎoshang hǎo, Ān!',
    exampleVietnamese: 'Chào buổi sáng, An!',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_13',
    character: '晚上好',
    pinyin: 'wǎnshang hǎo',
    definition: 'Chào buổi tối',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '大家晚上好！',
    examplePinyin: 'Dàjiā wǎnshang hǎo!',
    exampleVietnamese: 'Chào buổi tối mọi người!',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_14',
    character: '你好吗',
    pinyin: 'nǐ hǎo ma',
    definition: 'Bạn khỏe không',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '你好吗？我很好。',
    examplePinyin: 'Nǐ hǎo ma? Wǒ hěn hǎo.',
    exampleVietnamese: 'Bạn khỏe không? Tôi rất khỏe.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_15',
    character: '我很好',
    pinyin: 'wǒ hěn hǎo',
    definition: 'Tôi rất khỏe',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '谢谢，我很好。',
    examplePinyin: 'Xièxie, wǒ hěn hǎo.',
    exampleVietnamese: 'Cảm ơn, tôi rất khỏe.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_16',
    character: '谢谢',
    pinyin: 'xièxie',
    definition: 'Cảm ơn',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '谢谢老师。',
    examplePinyin: 'Xièxie lǎoshī.',
    exampleVietnamese: 'Cảm ơn thầy cô.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_17',
    character: '不客气',
    pinyin: 'bú kèqi',
    definition: 'Không có gì',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '不客气，这是我应该做的。',
    examplePinyin: 'Bú kèqi, zhè shì wǒ yīnggāi zuò de.',
    exampleVietnamese: 'Không có gì, đây là việc tôi nên làm.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_18',
    character: '对不起',
    pinyin: 'duìbuqǐ',
    definition: 'Xin lỗi',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '对不起，我迟到了。',
    examplePinyin: 'Duìbuqǐ, wǒ chídào le.',
    exampleVietnamese: 'Xin lỗi, tôi đến muộn.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_19',
    character: '没关系',
    pinyin: 'méi guānxi',
    definition: 'Không sao',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '没关系，不用谢。',
    examplePinyin: 'Méi guānxi, bú yòng xiè.',
    exampleVietnamese: 'Không sao đâu, không cần cảm ơn.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_20',
    character: '再见',
    pinyin: 'zàijiàn',
    definition: 'Tạm biệt',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '再见，明天见！',
    examplePinyin: 'Zàijiàn, míngtiān jiàn!',
    exampleVietnamese: 'Tạm biệt, ngày mai gặp lại!',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_21',
    character: '认识',
    pinyin: 'rènshi',
    definition: 'Quen / biết',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '认识你我很高兴。',
    examplePinyin: 'Rènshi nǐ wǒ hěn gāoxìng.',
    exampleVietnamese: 'Quen biết bạn tôi rất vui.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_22',
    character: '很高兴',
    pinyin: 'hěn gāoxìng',
    definition: 'Rất vui',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '今天我很高兴。',
    examplePinyin: 'Jīntiān wǒ hěn gāoxìng.',
    exampleVietnamese: 'Hôm nay tôi rất vui.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_23',
    character: '我叫',
    pinyin: 'wǒ jiào',
    definition: 'Tôi tên là',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '我叫明，我是越南人。',
    examplePinyin: 'Wǒ jiào Míng, wǒ shì Yuènánrén.',
    exampleVietnamese: 'Tôi tên Minh, tôi là người Việt Nam.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_24',
    character: '名字',
    pinyin: 'míngzi',
    definition: 'Tên',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '你的名字很好听。',
    examplePinyin: 'Nǐ de míngzi hěn hǎotīng.',
    exampleVietnamese: 'Tên của bạn nghe rất hay.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '0_25',
    character: '拜拜',
    pinyin: 'báibái',
    definition: 'Bye bye',
    category: 'Bài 0: Chào hỏi',
    exampleChinese: '我要走了，拜拜！',
    examplePinyin: 'Wǒ yào zǒu le, báibái!',
    exampleVietnamese: 'Tôi phải đi rồi, bye bye!',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '1',
    character: '是',
    pinyin: 'shì',
    definition: 'là (thì, đúng, vâng)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我是越南人。',
    examplePinyin: 'Wǒ shì Yuènánrén.',
    exampleVietnamese: 'Tôi là người Việt Nam.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '2',
    character: '不',
    pinyin: 'bù',
    definition: 'không (bất, dùng để phủ định)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我不是老师。',
    examplePinyin: 'Wǒ bú shì lǎoshī.',
    exampleVietnamese: 'Tôi không phải là giáo viên.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '3',
    character: '吗',
    pinyin: 'ma',
    definition: 'không? (trợ từ dùng ở cuối câu hỏi)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '你是学生吗？',
    examplePinyin: 'Nǐ shì xuésheng ma?',
    exampleVietnamese: 'Bạn là học sinh phải không?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '4',
    character: '也',
    pinyin: 'yě',
    definition: 'cũng (dùng biểu thị sự tương đồng)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我也是学生。',
    examplePinyin: 'Wǒ yě shì xuésheng.',
    exampleVietnamese: 'Tôi cũng là học sinh.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '5',
    character: '有',
    pinyin: 'yǒu',
    definition: 'có (sở hữu, tồn tại)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我有汉语老师。',
    examplePinyin: 'Wǒ yǒu Hànyǔ lǎoshī.',
    exampleVietnamese: 'Tôi có giáo viên tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '6',
    character: '怎么',
    pinyin: 'zěnme',
    definition: 'thế nào, làm sao, như thế nào',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '这个汉语字怎么说？',
    examplePinyin: 'Zhège Hànyǔ zì zěnme shuō?',
    exampleVietnamese: 'Chữ tiếng Trung này nói thế nào?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '7',
    character: '会',
    pinyin: 'huì',
    definition: 'biết, có thể (thông qua học tập)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我会说一点汉语。',
    examplePinyin: 'Wǒ huì shuō yìdiǎn Hànyǔ.',
    exampleVietnamese: 'Tôi biết nói một chút tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '8',
    character: '在',
    pinyin: 'zài',
    definition: 'ở, tại, đang (ở vị trí, hành động đang diễn ra)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '老师在公司工作。',
    examplePinyin: 'Lǎoshī zài gōngsī gōngzuò.',
    exampleVietnamese: 'Giáo viên đang làm việc ở công ty.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '9',
    character: '来',
    pinyin: 'lái',
    definition: 'đến, lại (hành động hướng về phía người nói)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '你来我家吧。',
    examplePinyin: 'Nǐ lái wǒ jiā ba.',
    exampleVietnamese: 'Bạn đến nhà tôi đi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '10',
    character: '从',
    pinyin: 'cóng',
    definition: 'từ (chỉ điểm xuất phát)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我从越南来。',
    examplePinyin: 'Wǒ cóng Yuènán lái.',
    exampleVietnamese: 'Tôi đến từ Việt Nam.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '11',
    character: '哪儿',
    pinyin: 'nǎr',
    definition: 'ở đâu, chỗ nào',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '现在你去哪儿？',
    examplePinyin: 'Xiànzài nǐ qù nǎr?',
    exampleVietnamese: 'Bây giờ bạn đi đâu?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '12',
    character: '现在',
    pinyin: 'xiànzài',
    definition: 'bây giờ, hiện tại',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '现在是学习时间。',
    examplePinyin: 'Xiànzài shì xuéxí shíjiān.',
    exampleVietnamese: 'Bây giờ là thời gian học tập.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '13',
    character: '这',
    pinyin: 'zhè',
    definition: 'đây, cái này (chỉ vật ở gần)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '这是我们的公司。',
    examplePinyin: 'Zhè shì wǒmen de gōngsī.',
    exampleVietnamese: 'Đây là công ty của chúng tôi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '14',
    character: '那',
    pinyin: 'nà',
    definition: 'kia, cái kia (chỉ vật ở xa)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '那是陈老师吗？',
    examplePinyin: 'Nà shì Chén lǎoshī ma?',
    exampleVietnamese: 'Kia là giáo viên Trần phải không?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '15',
    character: '人',
    pinyin: 'rén',
    definition: 'người (nhân)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '那个人是谁？',
    examplePinyin: 'Nàge rén shì shéi?',
    exampleVietnamese: 'Người kia là ai thế?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '16',
    character: '中国',
    pinyin: 'Zhōngguó',
    definition: 'Trung Quốc',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '有些学生去中国学习。',
    examplePinyin: 'Yǒuxiē xuésheng qù Zhōngguó xuéxí.',
    exampleVietnamese: 'Một số học sinh đi học ở Trung Quốc.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '17',
    character: '越南',
    pinyin: 'Yuènán',
    definition: 'Việt Nam',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我是越南人，我爱越南。',
    examplePinyin: 'Wǒ shì Yuènánrén, wǒ ài Yuènán.',
    exampleVietnamese: 'Tôi là người Việt Nam, tôi yêu Việt Nam.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '18',
    character: '汉语',
    pinyin: 'Hànyǔ',
    definition: 'tiếng Trung, tiếng Hoa (Hán ngữ)',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '他在公司说汉语。',
    examplePinyin: 'Tā zài gōngsī shuō Hànyǔ.',
    exampleVietnamese: 'Anh ấy nói tiếng Trung ở công ty.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '19',
    character: '工作',
    pinyin: 'gōngzuò',
    definition: 'công việc, làm việc',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '你的工作是什么？',
    examplePinyin: 'Nǐ de gōngzuò shì shénme?',
    exampleVietnamese: 'Công việc của bạn là gì?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '20',
    character: '学习',
    pinyin: 'xuéxí',
    definition: 'học tập, học hỏi',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我想学习说汉语。',
    examplePinyin: 'Wǒ xiǎng xuéxí shuō Hànyǔ.',
    exampleVietnamese: 'Tôi muốn học nói tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '21',
    character: '学生',
    pinyin: 'xuéshēng',
    definition: 'học sinh, sinh viên',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我们都是中国公司的学生。',
    examplePinyin: 'Wǒmen dōu shì Zhōngguó gōngsī de xuésheng.',
    exampleVietnamese: 'Chúng tôi đều là thực tập sinh/học viên của công ty Trung Quốc.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '22',
    character: '老师',
    pinyin: 'lǎoshī',
    definition: 'giáo viên, thầy cô giáo',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '王老师是很好的人。',
    examplePinyin: 'Wáng lǎoshī shì hěn hǎo de rén.',
    exampleVietnamese: 'Thầy Vương là một người rất tốt.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '23',
    character: '公司',
    pinyin: 'gōngsī',
    definition: 'công ty',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '你在哪个公司工作？',
    examplePinyin: 'Nǐ zài nǎge gōngsī gōngzuò?',
    exampleVietnamese: 'Bạn làm việc ở công ty nào?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '24',
    character: '说',
    pinyin: 'shuō',
    definition: 'nói',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '请慢一点说。',
    examplePinyin: 'Qǐng màn yìdiǎn shuō.',
    exampleVietnamese: 'Xin vui lòng nói chậm lại một chút.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '25',
    character: '一点',
    pinyin: 'yīdiǎn',
    definition: 'một chút, một ít',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我会说一点点汉语。',
    examplePinyin: 'Wǒ huì shuō yìdiǎndiǎn Hànyǔ.',
    exampleVietnamese: 'Tôi biết nói một chút xíu tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '51',
    character: '几',
    pinyin: 'jǐ',
    definition: 'mấy',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '你家有几个人？',
    examplePinyin: 'Nǐ jiā yǒu jǐ ge rén?',
    exampleVietnamese: 'Nhà bạn có mấy người?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '52',
    character: '岁',
    pinyin: 'suì',
    definition: 'tuổi',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '你今年几岁了？',
    examplePinyin: 'Nǐ jīnnián jǐ suì le?',
    exampleVietnamese: 'Năm nay bạn mấy tuổi rồi?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '53',
    character: '住',
    pinyin: 'zhù',
    definition: 'sống / ở',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '你现在住哪儿？',
    examplePinyin: 'Nǐ xiànzài zhù nǎr?',
    exampleVietnamese: 'Bây giờ bạn sống ở đâu?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '54',
    character: '还是',
    pinyin: 'háishì',
    definition: 'hay là / hoặc là',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '你是学生还是老师？',
    examplePinyin: 'Nǐ shì xuésheng háishì lǎoshī?',
    exampleVietnamese: 'Bạn là học sinh hay là giáo viên?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '55',
    character: '学校',
    pinyin: 'xuéxiào',
    definition: 'trường học',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我在学校学习汉语。',
    examplePinyin: 'Wǒ zài xuéxiào xuéxí Hànyǔ.',
    exampleVietnamese: 'Tôi học tiếng Trung ở trường.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '56',
    character: '可以',
    pinyin: 'kěyǐ',
    definition: 'có thể / được',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我可以去你的学校吗？',
    examplePinyin: 'Wǒ kěyǐ qù nǐ de xuéxiào ma?',
    exampleVietnamese: 'Tôi có thể đi đến trường của bạn không?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '57',
    character: '家',
    pinyin: 'jiā',
    definition: 'nhà / gia đình',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '这是我的家。',
    examplePinyin: 'Zhè shì wǒ de jiā.',
    exampleVietnamese: 'Đây là nhà của tôi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '58',
    character: '请问',
    pinyin: 'qǐngwèn',
    definition: 'xin hỏi',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '请问你叫什么名字？',
    examplePinyin: 'Qǐngwèn nǐ jiào shénme míngzi?',
    exampleVietnamese: 'Xin hỏi bạn tên là gì?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '59',
    character: '贵姓',
    pinyin: 'guìxìng',
    definition: 'quý tính / họ gì',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '请问您贵姓？',
    examplePinyin: 'Qǐngwèn nín guìxìng?',
    exampleVietnamese: 'Xin hỏi họ của ngài là gì?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '60',
    character: '爸爸',
    pinyin: 'bàba',
    definition: 'bố',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我爸爸是老师。',
    examplePinyin: 'Wǒ bàba shì lǎoshī.',
    exampleVietnamese: 'Bố tôi là giáo viên.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '61',
    character: '妈妈',
    pinyin: 'māma',
    definition: 'mẹ',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我妈妈不工作。',
    examplePinyin: 'Wǒ māma bù gōngzuò.',
    exampleVietnamese: 'Mẹ tôi không đi làm.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '62',
    character: '儿子',
    pinyin: 'érzi',
    definition: 'con trai',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '他有一个儿子。',
    examplePinyin: 'Tā yǒu yí ge érzi.',
    exampleVietnamese: 'Anh ấy có một người con trai.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '63',
    character: '女儿',
    pinyin: 'nǚ\'ér',
    definition: 'con gái',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我女儿今年三岁。',
    examplePinyin: 'Wǒ nǚ\'ér jīnnián sān suì.',
    exampleVietnamese: 'Con gái tôi năm nay ba tuổi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '64',
    character: '哥哥',
    pinyin: 'gēge',
    definition: 'anh trai',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我哥哥会说汉语。',
    examplePinyin: 'Wǒ gēge huì shuō Hànyǔ.',
    exampleVietnamese: 'Anh trai tôi biết nói tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '65',
    character: '弟弟',
    pinyin: 'dìdi',
    definition: 'em trai',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我弟弟是学生。',
    examplePinyin: 'Wǒ dìdi shì xuésheng.',
    exampleVietnamese: 'Em trai tôi là học sinh.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '66',
    character: '姐姐',
    pinyin: 'jiějie',
    definition: 'chị gái',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我姐姐在公司工作。',
    examplePinyin: 'Wǒ jiějie zài gōngsī gōngzuò.',
    exampleVietnamese: 'Chị gái tôi làm việc ở công ty.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '67',
    character: '妹妹',
    pinyin: 'mèimei',
    definition: 'em gái',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我妹妹很喜欢学习。',
    examplePinyin: 'Wǒ mèimei hěn xǐhuan xuéxí.',
    exampleVietnamese: 'Em gái tôi rất thích học tập.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '68',
    character: '爷爷',
    pinyin: 'yéye',
    definition: 'ông nội',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我爷爷住在越南。',
    examplePinyin: 'Wǒ yéye zhù zài Yuènán.',
    exampleVietnamese: 'Ông nội tôi sống ở Việt Nam.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '69',
    character: '奶奶',
    pinyin: 'nǎinai',
    definition: 'bà nội',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我奶奶今年七十岁。',
    examplePinyin: 'Wǒ nǎinai jīnnián qīshí suì.',
    exampleVietnamese: 'Bà nội tôi năm nay bảy mươi tuổi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '70',
    character: '外公',
    pinyin: 'wàigōng',
    definition: 'ông ngoại',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我外公很喜欢喝茶。',
    examplePinyin: 'Wǒ wàigōng hěn xǐhuan hē chá.',
    exampleVietnamese: 'Ông ngoại tôi rất thích uống trà.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '71',
    character: '外婆',
    pinyin: 'wàipó',
    definition: 'bà ngoại',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我外婆家有很多花。',
    examplePinyin: 'Wǒ wàipó jiā yǒu hěn duō huā.',
    exampleVietnamese: 'Nhà bà ngoại tôi có rất nhiều hoa.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '72',
    character: '叔叔',
    pinyin: 'shūshu',
    definition: 'chú',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '叔叔，请问现在几点？',
    examplePinyin: 'Shūshu, qǐngwèn xiànzài jǐ diǎn?',
    exampleVietnamese: 'Chú ơi, xin hỏi bây giờ là mấy giờ?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '73',
    character: '伯伯',
    pinyin: 'bóbo',
    definition: 'bác trai',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '李伯伯是我爸爸的朋友。',
    examplePinyin: 'Lǐ bóbo shì wǒ bàba de péngyou.',
    exampleVietnamese: 'Bác Lý là bạn của bố tôi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '74',
    character: '阿姨',
    pinyin: 'āyí',
    definition: 'cô / dì',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '阿姨，您好！',
    examplePinyin: 'Āyí, nín hǎo!',
    exampleVietnamese: 'Cháu chào cô ạ!',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '75',
    character: '舅舅',
    pinyin: 'jiùjiu',
    definition: 'cậu',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我舅舅在中国工作。',
    examplePinyin: 'Wǒ jiùjiu zài Zhōngguó gōngzuò.',
    exampleVietnamese: 'Cậu tôi làm việc ở Trung Quốc.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '76',
    character: '家人',
    pinyin: 'jiārén',
    definition: 'người nhà / gia đình',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '我爱我的家人。',
    examplePinyin: 'Wǒ ài wǒ de jiārén.',
    exampleVietnamese: 'Tôi yêu gia đình tôi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '77',
    character: '做',
    pinyin: 'zuò',
    definition: 'làm',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '她在做饭。',
    examplePinyin: 'Tā zài zuòfàn.',
    exampleVietnamese: 'Cô ấy đang nấu ăn.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '78',
    character: '最近',
    pinyin: 'zuìjìn',
    definition: 'dạo này / gần đây',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '你最近怎么样？',
    examplePinyin: 'Nǐ zuìjìn zěnmeyàng?',
    exampleVietnamese: 'Dạo này bạn thế nào?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '79',
    character: '朋友',
    pinyin: 'péngyou',
    definition: 'bạn bè / bạn hữu',
    category: 'Bài 1: Giới thiệu bản thân',
    exampleChinese: '他是我的朋友。',
    examplePinyin: 'Tā shì wǒ de péngyou.',
    exampleVietnamese: 'Anh ấy là bạn của tôi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '26',
    character: '时间',
    pinyin: 'shíjiān',
    definition: 'thời gian',
    category: 'Bài 2: Thời gian',
    exampleChinese: '我没有时间。',
    examplePinyin: 'Wǒ méiyǒu shíjiān.',
    exampleVietnamese: 'Tôi không có thời gian.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '27',
    character: '今天',
    pinyin: 'jīntiān',
    definition: 'hôm nay',
    category: 'Bài 2: Thời gian',
    exampleChinese: '今天我们去哪儿？',
    examplePinyin: 'Jīntiān wǒmen qù nǎr.',
    exampleVietnamese: 'Hôm nay chúng ta đi đâu?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '28',
    character: '明天',
    pinyin: 'míngtiān',
    definition: 'ngày mai',
    category: 'Bài 2: Thời gian',
    exampleChinese: '明天你来我家吗？',
    examplePinyin: 'Míngtiān nǐ lái wǒ jiā ma?',
    exampleVietnamese: 'Ngày mai bạn đến nhà tôi không?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '29',
    character: '昨天',
    pinyin: 'zuótiān',
    definition: 'hôm qua',
    category: 'Bài 2: Thời gian',
    exampleChinese: '昨天我没去公司。',
    examplePinyin: 'Zuótiān wǒ méi qù gōngsī.',
    exampleVietnamese: 'Hôm qua tôi không đến công ty.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '30',
    character: '现在',
    pinyin: 'xiànzài',
    definition: 'bây giờ',
    category: 'Bài 2: Thời gian',
    exampleChinese: '现在是十二点。',
    examplePinyin: 'Xiànzài shì shí\'èr diǎn.',
    exampleVietnamese: 'Bây giờ là 12 giờ.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '31',
    character: '以前',
    pinyin: 'yǐqián',
    definition: 'trước đây',
    category: 'Bài 2: Thời gian',
    exampleChinese: '以前他是我的学生。',
    examplePinyin: 'Yǐqián tā shì wǒ de xuésheng.',
    exampleVietnamese: 'Trước đây anh ấy là học sinh của tôi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '32',
    character: '以后',
    pinyin: 'yǐhòu',
    definition: 'sau này',
    category: 'Bài 2: Thời gian',
    exampleChinese: '以后我想去中国。',
    examplePinyin: 'Yǐhòu wǒ xiǎng qù Zhōngguó.',
    exampleVietnamese: 'Sau này tôi muốn đi Trung Quốc.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '33',
    character: '早上',
    pinyin: 'zǎoshang',
    definition: 'buổi sáng',
    category: 'Bài 2: Thời gian',
    exampleChinese: '早上我六点起床。',
    examplePinyin: 'Zǎoshang wǒ liù diǎn qǐchuáng.',
    exampleVietnamese: 'Buổi sáng tôi thức dậy lúc 6 giờ.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '34',
    character: '中午',
    pinyin: 'zhōngwǔ',
    definition: 'buổi trưa',
    category: 'Bài 2: Thời gian',
    exampleChinese: '中午你在哪儿吃饭？',
    examplePinyin: 'Zhōngwǔ nǐ zài nǎr chīfàn?',
    exampleVietnamese: 'Buổi trưa bạn ăn cơm ở đâu?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '35',
    character: '下午',
    pinyin: 'xiàwǔ',
    definition: 'buổi chiều',
    category: 'Bài 2: Thời gian',
    exampleChinese: '下午我有汉语课。',
    examplePinyin: 'Xiàwǔ wǒ yǒu Hànyǔ kè.',
    exampleVietnamese: 'Buổi chiều tôi có tiết học tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '36',
    character: '晚上',
    pinyin: 'wǎnshang',
    definition: 'buổi tối',
    category: 'Bài 2: Thời gian',
    exampleChinese: '晚上我学习汉语。',
    examplePinyin: 'Wǎnshang wǒ xuéxí Hànyǔ.',
    exampleVietnamese: 'Buổi tối tôi học tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '37',
    character: '上午',
    pinyin: 'shàngwǔ',
    definition: 'buổi sáng (trước trưa)',
    category: 'Bài 2: Thời gian',
    exampleChinese: '上午老师在公司。',
    examplePinyin: 'Shàngwǔ lǎoshī zài gōngsī.',
    exampleVietnamese: 'Buổi sáng giáo viên ở công ty.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '38',
    character: '分钟',
    pinyin: 'fēnzhōng',
    definition: 'phút',
    category: 'Bài 2: Thời gian',
    exampleChinese: '请等我十分钟。',
    examplePinyin: 'Qǐng děng wǒ shí fēnzhōng.',
    exampleVietnamese: 'Xin vui lòng đợi tôi 10 phút.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '39',
    character: '小时',
    pinyin: 'xiǎoshí',
    definition: 'giờ (tiếng)',
    category: 'Bài 2: Thời gian',
    exampleChinese: '我学习了两个小时。',
    examplePinyin: 'Wǒ xuéxí le liǎng ge xiǎoshí.',
    exampleVietnamese: 'Tôi đã học trong hai tiếng đồng hồ.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '40',
    character: '天',
    pinyin: 'tiān',
    definition: 'ngày',
    category: 'Bài 2: Thời gian',
    exampleChinese: '一天有二十四个小时。',
    examplePinyin: 'Yì tiān yǒu èrshísì ge xiǎoshí.',
    exampleVietnamese: 'Một ngày có 24 tiếng đồng hồ.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '41',
    character: '星期',
    pinyin: 'xīngqī',
    definition: 'tuần',
    category: 'Bài 2: Thời gian',
    exampleChinese: '这个星期我很忙。',
    examplePinyin: 'Zhège xīngqī wǒ hěn máng.',
    exampleVietnamese: 'Tuần này tôi rất bận.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '42',
    character: '月',
    pinyin: 'yuè',
    definition: 'tháng',
    category: 'Bài 2: Thời gian',
    exampleChinese: '今年五月我去中国。',
    examplePinyin: 'Jīnnián wǔyuè wǒ qù Zhōngguó.',
    exampleVietnamese: 'Tháng 5 năm nay tôi đi Trung Quốc.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '43',
    character: '年',
    pinyin: 'nián',
    definition: 'năm',
    category: 'Bài 2: Thời gian',
    exampleChinese: '他在中国学习了一年。',
    examplePinyin: 'Tā zài Zhōngguó xuéxí le yì nián.',
    exampleVietnamese: 'Anh ấy đã học ở Trung Quốc một năm.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '44',
    character: '早',
    pinyin: 'zǎo',
    definition: 'sớm',
    category: 'Bài 2: Thời gian',
    exampleChinese: '你来得很早。',
    examplePinyin: 'Nǐ lái de hěn zǎo.',
    exampleVietnamese: 'Bạn đến rất sớm.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '45',
    character: '晚',
    pinyin: 'wǎn',
    definition: 'muộn / tối',
    category: 'Bài 2: Thời gian',
    exampleChinese: '现在很晚了，去睡觉吧。',
    examplePinyin: 'Xiànzài hěn wǎn le, qù shuìjiào ba.',
    exampleVietnamese: 'Bây giờ muộn rồi, đi ngủ thôi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '46',
    character: '马上',
    pinyin: 'mǎshàng',
    definition: 'ngay lập tức',
    category: 'Bài 2: Thời gian',
    exampleChinese: '我马上来。',
    exampleVietnamese: 'Tôi đến ngay lập tức.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '47',
    character: '常常',
    pinyin: 'chángcháng',
    definition: 'thường xuyên',
    category: 'Bài 2: Thời gian',
    exampleChinese: '我常常和朋友说汉语。',
    examplePinyin: 'Wǒ chángcháng hé péngyou shuō Hànyǔ.',
    exampleVietnamese: 'Tôi thường xuyên nói tiếng Trung với bạn bè.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '48',
    character: '有时候',
    pinyin: 'yǒu shíhou',
    definition: 'đôi khi',
    category: 'Bài 2: Thời gian',
    exampleChinese: '有时候我不想工作。',
    examplePinyin: 'Yǒu shíhou wǒ bù xiǎng gōngzuò.',
    exampleVietnamese: 'Đôi khi tôi không muốn làm việc.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '49',
    character: '每天',
    pinyin: 'měitiān',
    definition: 'mỗi ngày',
    category: 'Bài 2: Thời gian',
    exampleChinese: '我每天都学习汉语。',
    examplePinyin: 'Wǒ měitiān dōu xuéxí Hànyǔ.',
    exampleVietnamese: 'Tôi học tiếng Trung mỗi ngày.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '50',
    character: '时候',
    pinyin: 'shíhou',
    definition: 'lúc, thời điểm',
    category: 'Bài 2: Thời gian',
    exampleChinese: '你什么时候去？',
    examplePinyin: 'Nǐ shénme shíhou qù?',
    exampleVietnamese: 'Khi nào bạn đi?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  }
];
