import { VocabularyWord } from './types';

export const INITIAL_VOCABULARY: VocabularyWord[] = [
  {
    id: '1',
    character: '是',
    pinyin: 'shì',
    definition: 'là (thì, đúng, vâng)',
    category: 'Bài 4: Từ mới I',
    exampleChinese: '我是越南人。',
    exampleVietnamese: 'Tôi là người Việt Nam.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '2',
    character: '不',
    pinyin: 'bù',
    definition: 'không (bất, dùng để phủ định)',
    category: 'Bài 4: Từ mới I',
    exampleChinese: '我不是老师。',
    exampleVietnamese: 'Tôi không phải là giáo viên.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '3',
    character: '吗',
    pinyin: 'ma',
    definition: 'không? (trợ từ dùng ở cuối câu hỏi)',
    category: 'Bài 4: Từ mới I',
    exampleChinese: '你是学生吗？',
    exampleVietnamese: 'Bạn là học sinh phải không?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '4',
    character: '也',
    pinyin: 'yě',
    definition: 'cũng (dùng biểu thị sự tương đồng)',
    category: 'Bài 4: Từ mới I',
    exampleChinese: '我也是学生。',
    exampleVietnamese: 'Tôi cũng là học sinh.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '5',
    character: '有',
    pinyin: 'yǒu',
    definition: 'có (sở hữu, tồn tại)',
    category: 'Bài 4: Từ mới I',
    exampleChinese: '我有汉语老师。',
    exampleVietnamese: 'Tôi có giáo viên tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '6',
    character: '怎么',
    pinyin: 'zěnme',
    definition: 'thế nào, làm sao, như thế nào',
    category: 'Bài 4: Từ mới I',
    exampleChinese: '这个汉语字怎么说？',
    exampleVietnamese: 'Chữ tiếng Trung này nói thế nào?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '7',
    character: '会',
    pinyin: 'huì',
    definition: 'biết, có thể (thông qua học tập)',
    category: 'Bài 4: Từ mới I',
    exampleChinese: '我会说一点汉语。',
    exampleVietnamese: 'Tôi biết nói một chút tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '8',
    character: '在',
    pinyin: 'zài',
    definition: 'ở, tại, đang (ở vị trí, hành động đang diễn ra)',
    category: 'Bài 4: Từ mới I',
    exampleChinese: '老师在公司工作。',
    exampleVietnamese: 'Giáo viên đang làm việc ở công ty.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '9',
    character: '来',
    pinyin: 'lái',
    definition: 'đến, lại (hành động hướng về phía người nói)',
    category: 'Bài 4: Từ mới I',
    exampleChinese: '你来我家吧。',
    exampleVietnamese: 'Bạn đến nhà tôi đi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '10',
    character: '从',
    pinyin: 'cóng',
    definition: 'từ (chỉ điểm xuất phát)',
    category: 'Bài 4: Từ mới I',
    exampleChinese: '我从越南来。',
    exampleVietnamese: 'Tôi đến từ Việt Nam.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '11',
    character: '哪儿',
    pinyin: 'nǎr',
    definition: 'ở đâu, chỗ nào',
    category: 'Bài 4: Từ mới I',
    exampleChinese: '现在你去哪儿？',
    exampleVietnamese: 'Bây giờ bạn đi đâu?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '12',
    character: '现在',
    pinyin: 'xiànzài',
    definition: 'bây giờ, hiện tại',
    category: 'Bài 4: Từ mới I',
    exampleChinese: '现在是学习时间。',
    exampleVietnamese: 'Bây giờ là thời gian học tập.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '13',
    character: '这',
    pinyin: 'zhè',
    definition: 'đây, cái này (chỉ vật ở gần)',
    category: 'Bài 4: Từ mới II',
    exampleChinese: '这是我们的公司。',
    exampleVietnamese: 'Đây là công ty của chúng tôi.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '14',
    character: '那',
    pinyin: 'nà',
    definition: 'kia, cái kia (chỉ vật ở xa)',
    category: 'Bài 4: Từ mới II',
    exampleChinese: '那是陈老师吗？',
    exampleVietnamese: 'Kia là giáo viên Trần phải không?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '15',
    character: '人',
    pinyin: 'rén',
    definition: 'người (nhân)',
    category: 'Bài 4: Từ mới II',
    exampleChinese: '那个人是谁？',
    exampleVietnamese: 'Người kia là ai thế?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '16',
    character: '中国',
    pinyin: 'Zhōngguó',
    definition: 'Trung Quốc',
    category: 'Bài 4: Từ mới II',
    exampleChinese: '有些学生去中国学习。',
    exampleVietnamese: 'Một số học sinh đi học ở Trung Quốc.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '17',
    character: '越南',
    pinyin: 'Yuènán',
    definition: 'Việt Nam',
    category: 'Bài 4: Từ mới II',
    exampleChinese: '我是越南人，我爱越南。',
    exampleVietnamese: 'Tôi là người Việt Nam, tôi yêu Việt Nam.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '18',
    character: '汉语',
    pinyin: 'Hànyǔ',
    definition: 'tiếng Trung, tiếng Hoa (Hán ngữ)',
    category: 'Bài 4: Từ mới II',
    exampleChinese: '他在公司说汉语。',
    exampleVietnamese: 'Anh ấy nói tiếng Trung ở công ty.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '19',
    character: '工作',
    pinyin: 'gōngzuò',
    definition: 'công việc, làm việc',
    category: 'Bài 4: Từ mới II',
    exampleChinese: '你的工作是什么？',
    exampleVietnamese: 'Công việc của bạn là gì?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '20',
    character: '学习',
    pinyin: 'xuéxí',
    definition: 'học tập, học hỏi',
    category: 'Bài 4: Từ mới II',
    exampleChinese: '我想学习说汉语。',
    exampleVietnamese: 'Tôi muốn học nói tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '21',
    character: '学生',
    pinyin: 'xuéshēng',
    definition: 'học sinh, sinh viên',
    category: 'Bài 4: Từ mới II',
    exampleChinese: '我们都是中国公司的学生。',
    exampleVietnamese: 'Chúng tôi đều là thực tập sinh/học viên của công ty Trung Quốc.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '22',
    character: '老师',
    pinyin: 'lǎoshī',
    definition: 'giáo viên, thầy cô giáo',
    category: 'Bài 4: Từ mới II',
    exampleChinese: '王老师是很好的人。',
    exampleVietnamese: 'Thầy Vương là một người rất tốt.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '23',
    character: '公司',
    pinyin: 'gōngsī',
    definition: 'công ty',
    category: 'Bài 4: Từ mới II',
    exampleChinese: '你在哪个公司工作？',
    exampleVietnamese: 'Bạn làm việc ở công ty nào?',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '24',
    character: '说',
    pinyin: 'shuō',
    definition: 'nói',
    category: 'Bài 4: Từ mới II',
    exampleChinese: '请慢一点说。',
    exampleVietnamese: 'Xin vui lòng nói chậm lại một chút.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  },
  {
    id: '25',
    character: '一点',
    pinyin: 'yīdiǎn',
    definition: 'một chút, một ít',
    category: 'Bài 4: Từ mới II',
    exampleChinese: '我会说一点点汉语。',
    exampleVietnamese: 'Tôi biết nói một chút xíu tiếng Trung.',
    correctCount: 0,
    incorrectCount: 0,
    status: 'new'
  }
];
